### ISSUE TITLE
Leverage DKIM Authentication-Results

### ISSUE THREAD

**Issue by pinkforest** [fluvio-connectors/imap-connector#4]
Modern e-mail infrastructure implements Authentication-Results header

This header includes the passage on what the incoming e-mail server thinks about the status of Domainkeys Identified Mail (DKIM) Signatures verification.

We can use this status to create conditional e-mail pipelines.

What we can also do w/o copying is "move" e-mails between IMAP folders according to it's authenticated status.

I've published parser and verifier library [msg-auth-status](https://crates.io/crates/msg-auth-status) that I can leverage for this.

**Comment by sehz** [comment]
This would be good for SDF.  Can you check if this compiles to WASI?

**Comment by pinkforest** [comment]
msg-auth-status does - 

```
$ cargo build --all-features --target wasm32-wasi
  Downloaded syn v2.0.68
  Downloaded 1 crate (265.0 KB) in 0.14s
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling beef v0.5.2
   Compiling fnv v1.0.7
   Compiling regex-syntax v0.8.4
   Compiling lazy_static v1.5.0
   Compiling mail-parser v0.9.3
   Compiling quote v1.0.36
   Compiling syn v2.0.68
   Compiling logos-codegen v0.14.0
   Compiling logos-derive v0.14.0
   Compiling logos v0.14.0
   Compiling msg-auth-status v0.2.0 (/home/foobar/code/areweat/msg-auth-status)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 13.70s
```

If connectors would be going wasi we would need to switch from async-std that is used by all connectors .. I think

I also have no_std protocol implementations that allow operating in both host io_uring & wasm guest as sans-io if needed
